language: julia
os:
  - linux
  - osx

julia:
  - 1.1
  - nightly

codecov: true

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  exclude:
    - os: windows
      julia: nightly
      language: julia

  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia

  allow_failures:
  - julia: nightly
  - os: osx
  - os: windows

addons:
  apt_packages:
    - gfortran

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
